{% set version = "1.4.2" %}

package:
  name: kiwisolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-{{ version }}.tar.gz
  sha256: 7f606d91b8a8816be476513a77fd30abe66227039bd6f8b406c348cb0247dcc9

build:
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cppy >=1.2.0
    - setuptools >=61.2
    - setuptools-scm >=3.4.3
    - toml
    - wheel
  run:
    - python
    - typing_extensions  # [py<38]

test:
  imports:
    - kiwisolver
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: An efficient C++ implementation of the Cassowary constraint solver
  description: |
    Kiwi is an implementation of the algorithm based on the seminal
    Cassowary paper.It is not a refactoring of the original C++ solver.
    Kiwi has been designed from the ground up to be lightweight and fast.
  doc_url: https://pypi.python.org/pypi/kiwisolver
  doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
  dev_url: https://github.com/nucleic/kiwi

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
    - ocefpaf
