{% set version = "1.1.0" %}

package:
  name: kiwisolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-{{ version }}.tar.gz
  sha256: 53eaed412477c836e1b9522c19858a8557d6e595077830146182225613b11a75

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - kiwisolver

about:
  home: https://github.com/nucleic/kiwi
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient C++ implementation of the Cassowary constraint solver
  description: |
    Kiwi is an implementation of the algorithm based on the seminal
    Cassowary paper.It is not a refactoring of the original C++ solver.
    Kiwi has been designed from the ground up to be lightweight and fast.
  doc_url: https://pypi.python.org/pypi/kiwisolver
  doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
  dev_url: https://github.com/nucleic/kiwi
  summary: A fast implementation of the Cassowary constraint solver

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
    - ocefpaf
