{% set version = "1.3.2" %}

package:
  name: kiwisolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-{{ version }}.tar.gz
  sha256: fc4453705b81d03568d5b808ad8f09c77c47534f6ac2e72e733f9ca4714aa75c

build:
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cppy >=1.1.0
    - wheel
  run:
    - python >=3.7

test:
  imports:
    - kiwisolver
  requires:
    - pip
    - python <3.10
  commands:
    - pip check

about:
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: An efficient C++ implementation of the Cassowary constraint solver
  description: |
    Kiwi is an implementation of the algorithm based on the seminal
    Cassowary paper.It is not a refactoring of the original C++ solver.
    Kiwi has been designed from the ground up to be lightweight and fast.
  doc_url: https://pypi.python.org/pypi/kiwisolver
  doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
  dev_url: https://github.com/nucleic/kiwi

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
    - ocefpaf
