travis:
  secure:
    BINSTAR_TOKEN: EsltmCI9jhIrXvsdhB0jJ0dQBe5CSvbUQdT8Oqb9g7EbqE4CV065ycEbmw67gX+DGeZpge6PGc3yGyYpFyjT9HYVsKnqlAnyyc9DMYaFYAXbz24w5gdaVplL4qTFeut2sXqbU0Dj252CU52uvrejU37D4ucapFMe1eCDMTAyUMQtU8UHBi9W/AiEJ1dtiyni8Rjbi0ThZ3S/02R+L6RWIp3uUB5Bk2ez1nlTAsyQcUlcv6H/5EcLzuw1lK9FQZ6IacnUu8kDDoJby9yYZyg9pNlMt2SIqpLwZ12LeZJEq+QsMtEwk6o1FV2wK79Issswb1WjEvxSd5qVFqtDsu6BHsJ52TzhvEvU7R9fT+S882Ydnt1rOjJnaBJKqUwegZ5JKkYk233fdHqsxwpKu2KixrvcAtpNUSA0ZyPFZP2DIae7J1Ihy6ljc99xcnuhFSKiyzT/z6bUDl/xhOxq5JXebyxO4eyPowrP9Yc9Ek2t0yfayYxnMlukzkLIfOLIttgjkvpHAeJt1IX6ZHtLyTBP7/gZxQat8fJmtUUu6fjI1nZmPSdV6v6/19Ghg89eSXi5qKYhv3ejb91P7X9g7bMT1Tu4pAcF9tOjVfm6rTCg+7cw6EmDIs05JZjhNKMcBA/Pcgu5TvxR23EadsJ5T7YRgEEIjJs+zXvWDpmc992azb8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
