travis:
  secure:
    BINSTAR_TOKEN: g6DWiopnAlzRR0hOfipEg49nlxC8diAIox8TBpEEga2MqLXAt346YH7yYVjmXj/BvtpLZK2m4b83hNlSg+O5un45BLYrD5LETyxJEjr/HMzy0LmW/i0n2vN+4Zpvm/yKAJisfwFX8/NSmXM7XddDNXts43U3hrYTvOSzUYIXM8rUmuq4NyXT39bNTKoZ3bMrSC4baMq/3MluUTqo7ZEZMm176P9Gr+JlgpwDvjp8VEP/GMrJf/PfdhWfAfayoFMvFjIsrqZ/w/P6J6Y6nqkEx9pgftHI9Z+hMQHbHkAopVTJOJ/E1I0BCEH/O4onUs986C9c59ZWtyEv5kVZ+CSjzuXFsCxb0IiZoICHTsZuZFFTbWXDzQT4VRar4Eln5XhuF3II6Gzr10epDi3JmIR/bbY9i0gF4t+oDolaKpPCujg+lfc7vlOHHyjshdepPndAHBosyCg+sSu47jnq4OTJdV6SJbSRED0qfaq96zpzYEWFtMr2eVzmax8cMEVhmx5bx+XS5o23bJDoICDl3nO4BpXUMYNXfE81los7nxje1XwYnJu/l1zznM/SCmCm6cUHoaTfiCO13/8A8ZKpFramQyOBV1pZ+i4cvfH4gksNdM3benG0RoGFmSfp5WgwGATayRSSRtRwWqRO5JBrVtak4LPzlnaiMt9NXK9qLzKzAAc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
