travis:
  secure:
    BINSTAR_TOKEN: MqTrQU7TIKupmp+GszP1Mpnfi2MPG8qfdxsLXM2pL1TYX7Acc++84cu5KEie7+LbfHAcYuZBxLqfbL96CINLktM1bKXnuIu4Dmt0oIS30mftlR4tFwaPqOq7bABJ1o1IrcU3FSTz6YuATWwNb84v5fMX6To7ABStPEesbRtIP3809SlluQgsLQw+rVGlOpf+laEj+jGMoat+JJrB7q96HdeeGTLj6U6dnFtobmOCfJPJebK8q/c9VntjGs+BvJtoNNoQy10XA3+zTUTiKaMydm0F+HJBkqJlIGy7oAmEB6UcYe8/DQBNusimazQ7W5h5tC9H4uGYzItCka1/Y/3iqYU/xLmV+mEJILieuTVe9NOuhXjspDcv7/V8Ogq76wQB4423wWNsvJIi/YN5MNuPLVU62JyuNeJ7GYPFKGelt9xSvcEgGWKLjNmP0wT1yxT2OQ5O5De2qIqv5WbJr+B1fng1zcEW+r6HNDifbMrPl8R2JDztfOlT6mrUaVcaMSbnOSMCsMO/aRtG5G0CtWKCN2AMxQ+mqNSABi63e6eKXWasdZ5np1oFdbc2ceS3A3RCNF8WfIhf7/sfbZgVoZ8o5T6X4keDoMvSs/cL70olSpuJgwE381UAIN+/whjv4XCOZEIhYT6ugAi4i9ahmMCf6p3C9qAseT0fMQtr5DKWvn8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
